players_columns = [
    'player_assists',
    'player_bonus',
    'player_can_select',
    'player_can_transact',
    'player_chance_of_playing_next_round',
    'player_chance_of_playing_this_round',
    'player_clean_sheets',
    'player_clean_sheets_per_90',
    'player_clearances_blocks_interceptions',
    'player_cost_change_event',
    'player_cost_change_event_fall',
    'player_cost_change_start',
    'player_cost_change_start_fall',
    'player_defensive_contribution',
    'player_defensive_contribution_per_90',
    'player_event_points',
    'player_expected_assists',
    'player_expected_assists_per_90',
    'player_expected_goal_involvements',
    'player_expected_goal_involvements_per_90',
    'player_expected_goals',
    'player_expected_goals_conceded',
    'player_expected_goals_conceded_per_90',
    'player_expected_goals_per_90',
    'player_first_name',
    'player_form',
    'player_goals_conceded',
    'player_goals_conceded_per_90',
    'player_goals_scored',
    'player_id',
    'player_in_dreamteam',
    'player_known_name',
    'player_minutes',
    'player_now_cost',
    'player_now_cost_rank',
    'player_own_goals',
    'player_penalties_missed',
    'player_penalties_order',
    'player_penalties_saved',
    'player_points_per_game',
    'player_price_change_percent',
    'player_recoveries',
    'player_red_cards',
    'player_saves',
    'player_saves_per_90',
    'player_second_name',
    'player_selected_by_percent',
    'player_selected_rank',
    'player_starts',
    'player_starts_per_90',
    'player_status',
    'player_tackles',
    'player_threat',
    'player_total_points',
    'player_transfers_in',
    'player_transfers_in_event',
    'player_transfers_out',
    'player_transfers_out_event',
    'player_value_form',
    'player_value_season',
    'player_yellow_cards',
    'player_element_type',
    'is_captain',
    'is_vice_captain',
    'purchase_price'
]


teams_columns = [
    "team_code",
    "team_id",
    "team_name",
    "team_short_name"
]

element_types = {
    '1' : {
        'plural_name' : 'Goalkeepers',
        'singular_name' : 'Goalkeeper',
        'singular_name_short' : 'GKP',
    },
    '2' : {
        'plural_name' : 'Defenders',
        'singular_name' : 'Defender',
        'singular_name_short' : 'DEF',
    },
    '3' : {
        'plural_name' : 'Midfielders',
        'singular_name' : 'Midfielder',
        'singular_name_short' : 'MID',
    },
    '4' : {
        'plural_name' : 'Forwards',
        'singular_name' : 'Forward',
        'singular_name_short' : 'FWD',
    }
}