players_columns = [
    'player.assists',
    'player.bonus',
    'player.can_select',
    'player.can_transact',
    'player.chance_of_playing_next_round',
    'player.chance_of_playing_this_round',
    'player.clean_sheets',
    'player.clean_sheets_per_90',
    'player.clearances_blocks_interceptions',
    'player.cost_change_event',
    'player.cost_change_event_fall',
    'player.cost_change_start',
    'player.cost_change_start_fall',
    'player.defensive_contribution',
    'player.defensive_contribution_per_90',
    'player.event_points',
    'player.expected_assists',
    'player.expected_assists_per_90',
    'player.expected_goal_involvements',
    'player.expected_goal_involvements_per_90',
    'player.expected_goals',
    'player.expected_goals_conceded',
    'player.expected_goals_conceded_per_90',
    'player.expected_goals_per_90',
    'player.first_name',
    'player.form',
    'player.goals_conceded',
    'player.goals_conceded_per_90',
    'player.goals_scored',
    'player.id',
    'player.in_dreamteam',
    'player.known_name',
    'player.minutes',
    'player.now_cost',
    'player.now_cost_rank',
    'player.own_goals',
    'player.penalties_missed',
    'player.penalties_order',
    'player.penalties_saved',
    'player.points_per_game',
    'player.price_change_percent',
    'player.recoveries',
    'player.red_cards',
    'player.saves',
    'player.saves_per_90',
    'player.second_name',
    'player.selected_by_percent',
    'player.selected_rank',
    'player.starts',
    'player.starts_per_90',
    'player.status',
    'player.tackles',
    'player.threat',
    'player.total_points',
    'player.transfers_in',
    'player.transfers_in_event',
    'player.transfers_out',
    'player.transfers_out_event',
    'player.value_form',
    'player.value_season',
    'player.yellow_cards',
    'player.element_type',
    'is_captain',
    'is_vice_captain',
    'purchase_price'
]


teams_columns = [
    "team.code",
    "team.id",
    "team.name",
    "team.short_name"
]

element_types = {
    '1' : {
        'plural_name' : 'Goalkeepers',
        'singular_name' : 'Goalkeeper',
        'singular_name_short' : 'GKP',
    },
    '2' : {
        'plural_name' : 'Defenders',
        'singular_name' : 'Defender',
        'singular_name_short' : 'DEF',
    },
    '3' : {
        'plural_name' : 'Midfielders',
        'singular_name' : 'Midfielder',
        'singular_name_short' : 'MID',
    },
    '4' : {
        'plural_name' : 'Forwards',
        'singular_name' : 'Forward',
        'singular_name_short' : 'FWD',
    }
}