players_columns = [
    'players.assists',
    'players.bonus',
    'players.can_select',
    'players.can_transact',
    'players.chance_of_playing_next_round',
    'players.chance_of_playing_this_round',
    'players.clean_sheets',
    'players.clean_sheets_per_90',
    'players.clearances_blocks_interceptions',
    'players.cost_change_event',
    'players.cost_change_event_fall',
    'players.cost_change_start',
    'players.cost_change_start_fall',
    'players.defensive_contribution',
    'players.defensive_contribution_per_90',
    'players.event_points',
    'players.expected_assists',
    'players.expected_assists_per_90',
    'players.expected_goal_involvements',
    'players.expected_goal_involvements_per_90',
    'players.expected_goals',
    'players.expected_goals_conceded',
    'players.expected_goals_conceded_per_90',
    'players.expected_goals_per_90',
    'players.first_name',
    'players.form',
    'players.goals_conceded',
    'players.goals_conceded_per_90',
    'players.goals_scored',
    'players.id',
    'players.in_dreamteam',
    'players.known_name',
    'players.minutes',
    'players.now_cost',
    'players.now_cost_rank',
    'players.own_goals',
    'players.penalties_missed',
    'players.penalties_order',
    'players.penalties_saved',
    'players.points_per_game',
    'players.price_change_percent',
    'players.recoveries',
    'players.red_cards',
    'players.saves',
    'players.saves_per_90',
    'players.second_name',
    'players.selected_by_percent',
    'players.selected_rank',
    'players.starts',
    'players.starts_per_90',
    'players.status',
    'players.tackles',
    'players.threat',
    'players.total_points',
    'players.transfers_in',
    'players.transfers_in_event',
    'players.transfers_out',
    'players.transfers_out_event',
    'players.value_form',
    'players.value_season',
    'players.yellow_cards',
    'is_captain',
    'is_vice_captain',
    'purchase_price'
]


teams_columns = [
    "teams.code",
    "teams.id",
    "teams.name",
    "teams.short_name"
]

element_types = {
    '1' : {
        'plural_name' : 'Goalkeepers',
        'singular_name' : 'Goalkeeper',
        'singular_name_short' : 'GKP',
    },
    '2' : {
        'plural_name' : 'Defenders',
        'singular_name' : 'Defender',
        'singular_name_short' : 'DEF',
    },
    '3' : {
        'plural_name' : 'Midfielders',
        'singular_name' : 'Midfielder',
        'singular_name_short' : 'MID',
    },
    '4' : {
        'plural_name' : 'Forwards',
        'singular_name' : 'Forward',
        'singular_name_short' : 'FWD',
    }
}